name: Deploy android to Google Play
on:
  push:
    branches:
      - master
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install npm dependencies
        run: |
          yarn
      - name: Build android aab
        run: |
          cd android
          echo "AWAL_I_WASS_ARABIC_UPLOAD_KEY_ALIAS=${{ secrets.AWAL_I_WASS_ARABIC_UPLOAD_KEY_ALIAS }}" >> gradle.properties
          echo "AWAL_I_WASS_ARABIC_UPLOAD_STORE_FILE=${{ secrets.AWAL_I_WASS_ARABIC_UPLOAD_STORE_FILE }}" >> gradle.properties
          echo "AWAL_I_WASS_ARABIC_UPLOAD_STORE_PASSWORD=${{ secrets.AWAL_I_WASS_ARABIC_UPLOAD_STORE_PASSWORD }}" >> gradle.properties
          echo "AWAL_I_WASS_ARABIC_UPLOAD_KEY_PASSWORD=${{ secrets.AWAL_I_WASS_ARABIC_UPLOAD_KEY_PASSWORD }}" >> gradle.properties
          ./gradlew bundleRelease
      - name: upload bundle to Google Play
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName: com.wordofgodforeachday.arabic
          releaseFiles: android/app/build/outputs/bundle/release/*.aab
          track: production
          #userFraction: 0.33
          whatsNewDirectory: whatsnew
          #mappingFile: /app/build/outputs/mapping/release/mapping.txt
          status: completed